NetrunnerdbCardsBundle_admin_cycle:
    resource: "@NetrunnerdbCardsBundle/Resources/config/routing/cycle.yml"
    prefix:   /admin/cycle

NetrunnerdbCardsBundle_admin_pack:
    resource: "@NetrunnerdbCardsBundle/Resources/config/routing/pack.yml"
    prefix:   /admin/pack

NetrunnerdbCardsBundle_admin_card:
    resource: "@NetrunnerdbCardsBundle/Resources/config/routing/card.yml"
    prefix:   /admin/card

netrunnerdb_netrunner_cards_list:
    pattern:  /{_locale}/set/{pack_code}/{view}/{sort}
    defaults:
        _controller: NetrunnerdbCardsBundle:Search:list
        _locale: en
        view: list
        sort: set
    requirements:
        _locale: en|fr|de|es|it|pl

netrunnerdb_netrunner_cards_zoom:
    pattern:  /{_locale}/card/{card_code}
    defaults:
        _controller: NetrunnerdbCardsBundle:Search:zoom
        _locale: en
    requirements:
        _locale: en|fr|de|es|it|pl
        card_code: \d+

netrunnerdb_netrunner_cards_cycle:
    pattern:  /{_locale}/cycle/{cycle_code}/{view}/{sort}
    defaults:
        _controller: NetrunnerdbCardsBundle:Search:cycle
        _locale: en
        view: list
        sort: faction
    requirements:
        _locale: en|fr|de|es|it|pl

netrunnerdb_netrunner_cards_search:
    pattern:  /{_locale}/search
    defaults:
        _controller: NetrunnerdbCardsBundle:Default:search
        _locale: en
    requirements:
        _locale: en|fr|de|es|it|pl

netrunnerdb_netrunner_cards_find:
    pattern:  /find/
    defaults:
        _controller: NetrunnerdbCardsBundle:Search:find

netrunnerdb_netrunner_cards_processSearchForm:
    pattern:  /process/
    defaults:
        _controller: NetrunnerdbCardsBundle:Search:process

netrunnerdb_netrunner_cards_about:
    pattern:  /{_locale}/about
    defaults:
        _controller: NetrunnerdbCardsBundle:Default:about
        _locale: en
    requirements:
        _locale: en|fr|de|es|it|pl

netrunnerdb_netrunner_cards_changelog:
    pattern:  /{_locale}/changelog
    defaults:
        _controller: NetrunnerdbCardsBundle:Default:changelog
        _locale: en
    requirements:
        _locale: en|fr|de|es|it|pl

netrunnerdb_netrunner_cards_api:
    pattern:  /{_locale}/apidoc
    defaults:
        _controller: NetrunnerdbCardsBundle:Default:apidoc
        _locale: en
    requirements:
        _locale: en|fr|de|es|it|pl

netrunnerdb_netrunner_cards_rulings:
    pattern:  /{_locale}/rules
    defaults:
        _controller: NetrunnerdbCardsBundle:Default:rules
        _locale: en
    requirements:
        _locale: en|fr|de|es|it|pl

api_cards:
    pattern: /api/cards/
    defaults:
        _controller: NetrunnerdbCardsBundle:Search:apicards

api_card:
    pattern: /api/card/{card_code}.{_format}
    defaults:
        _controller: NetrunnerdbCardsBundle:Search:apicard
        _format: json
    requirements:
        _format: json
        card_code: \d+

api_sets:
    pattern: /api/sets/
    defaults:
        _controller: NetrunnerdbCardsBundle:Default:apisets

api_set:
    pattern: /api/set/{pack_code}.{_format}
    defaults:
        _controller: NetrunnerdbCardsBundle:Search:apiset
        _format: json
    requirements:
        _format: json|xml

NetrunnerdbCardsBundle_admin_cards:
    resource: "@NetrunnerdbCardsBundle/Resources/config/routing/cards.yml"
    prefix:   /admin/cards

NetrunnerdbCardsBundle_admin_rulings:
    resource: "@NetrunnerdbCardsBundle/Resources/config/routing/rulings.yml"
    prefix:   /admin/rulings

NetrunnerdbCardsBundle_admin_rxc:
    resource: "@NetrunnerdbCardsBundle/Resources/config/routing/rxc.yml"
    prefix:   /admin/rxc

card_opinion:
    pattern: /user/opinion
    defaults:
        _controller: NetrunnerdbCardsBundle:Search:opinion
    methods: [POST]


all_opinions:
    pattern: /{_locale}/cardcomments/{page}
    defaults:
        _controller: NetrunnerdbCardsBundle:Search:opinions
        page: 1
    requirements:
        _locale: en|fr|de|es|it|pl

ffg:
    pattern: /ffg
    defaults:
        _controller: NetrunnerdbCardsBundle:Default:ffg
